### ISSUE TITLE
Displays OCR in a viewers following the IIIF Presentation API

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#15]
# Summary

We have found that transcripts as annotations are often not desirable. They tend to substantially expand what is in the IIIF manifest. So far, we’ve only implemented transcript data display outside of the UV. Having said that, adding this field to a manifest is not that complex. The complexity is all on the display side. 

**Should this display like transcripts, or just provide searchable text.  How will this look?**

**Comment by jillpe** [comment]
covered in #358
