### ISSUE TITLE
Implementing Range: URI according to DC MAP

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/utk-hyku#161]
### Descriptive summary

On the [Digital Collections: Vendor Supplied MAP](https://docs.google.com/spreadsheets/d/1_0QVbQU_wj3ITUih5dGPGkWHN0QyhGO9hKSf6rXwKPc/edit#gid=365080784), the `Collection` sheet's `column E`: `Range` sometimes has the value `URI` (as opposed to `String` or `Date`).  This ticket is to track what `Range`: `URI` means and how to implement it. 

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by ShanaLMoore** [comment]
@DiemBTran Thanks for creating this ticket and for asking this question. 

We discussed it during a [meeting](https://docs.google.com/document/d/1PDZsGDeZUh9b7BrzsyprmRZOCT4GEwNCg5FXBzyRCUU/edit?usp=sharing) last week and it was determined that ranges aren't enforced yet, and they probably won't ever be. So there is currently no expectations that something will behave a certain way depending on its value. 

For that reason I am going to close this ticket.
