### ISSUE TITLE
Google Scholar

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#29]
# Summary

It is important that works can be properly found and searched in google scholar, so proper metadata tags will need to be used for scholarly works.  

# Acceptance Criteria
- [ ] Worktypes for scholarly data have tags for google scholar

# Screenshots/Videos

# Testing Instructions

# Notes
- information on google scholar indexing - https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

**Comment by DiemBTran** [comment]
Mark May 2022

---

Adding that our MAP has a column dedicated to the metatags we believe should be mapped here for Google Scholar inclusion:

https://docs.google.com/spreadsheets/d/1QwsmpbL-KtlQpKxe5t40RXZHw9IZXrwkeTMobQ4N-CM/edit?usp=sharing

**Comment by DiemBTran** [comment]
Shana May 2022

---

https://github.com/curationexperts/schoolie

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
