### ISSUE TITLE
Figma redesign - Remove browse collections from homepage

### ISSUE THREAD

**Issue by AKFosterDev** [scientist-softserv/utk-hyku#324]
## Summary
Complete new figma design for removing the browse collections section from the homepage and move the "view all collections" button to the featured collections section of the homepage.

## Related Tickets
Re-work ticket - [#320](https://github.com/scientist-softserv/utk-hyku/issues/320)
Original tickets - [#259](https://github.com/scientist-softserv/utk-hyku/issues/259) & [#260](https://github.com/scientist-softserv/utk-hyku/issues/260)

## Screenshots
**New Design for Approval**

- [x] Approved by client

![Image](https://user-images.githubusercontent.com/39319859/217584628-9074f777-ae6a-4b04-af12-0923c9825c4e.JPG)

**Original Design**

![image](https://user-images.githubusercontent.com/39319859/217056878-4353c540-aeee-4b35-a4da-3f99cd13e78d.png)

**Comment by AKFosterDev** [comment]
Figma design updated to reflect client's requested changes. Screenshot above in summary.

Figma design [here](https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=0%3A1&t=3eagmd4ElvyPGl2q-1).

**Comment by mlhale7** [comment]
Thanks for this @AKFosterDev. This addresses the change we requested to no longer list all collections below the featured collections.
