### ISSUE TITLE
DC Repository Login Page

### ISSUE THREAD

**Issue by DeonFranklin** [scientist-softserv/utk-hyku#329]
## Summary

Update design for DC repository log in page.

## Acceptance Criteria:

- [x] Login page is styled to match the proposed design screenshot below
- [x] Login page is responsive

## Screenshots
**Proposed Design for client approval**
- [x] Approved by client

![proposed login page design](https://user-images.githubusercontent.com/39319859/217623335-39ebb059-530d-4f46-9359-b61fe3d7382f.JPG)

**Current**
![log in page](https://user-images.githubusercontent.com/39319859/217617477-34ef7a9c-cec1-469c-af71-96c55138856f.JPG)

**Comment by AKFosterDev** [comment]
Marked blocked - Waiting for client approval of proposed design screenshot above.

**Comment by AKFosterDev** [comment]
Ticket moved to Client QA - Need client approval of above proposed design.

**Comment by josh-morgan117** [comment]
Has this been deployed for staging? Can't tell the responsive from screenshots.

**Comment by AKFosterDev** [comment]
Hi @kidon0011. Right now we need confirmation that you are happy with the design proposed in the screenshot above. The changes you see in the screenshot were done quickly in the browser inspector. The changes made were mainly spacing and some font changes. We need approval on the design before we start working on the code. The page will be responsive once the code is complete. Hope that clarifies.

**Comment by josh-morgan117** [comment]
@AKFosterDev Thanks, I'll go ahead and approve it.

**Comment by AKFosterDev** [comment]
Related PR [i329 DC Log In Page](https://github.com/scientist-softserv/utk-hyku/pull/341)
