### ISSUE TITLE
Update IIIF print

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/utk-hyku#433]
# Summary
Update IIIF print, not including the derivative rodeo/spacestone work. Then test #421 and #422 to see if they are resolved or not.

# Accepted Criteria
- [ ] IIIF print is updated and does not include derivative rodeo/spacestone work

**Comment by jeremyf** [comment]
It should be okay to include the derivative rodeo commits, as those are not configured to be run/used.

**Comment by kirkkwang** [comment]
closing this ticket since QA is covered by

- #421
- #422
