### ISSUE TITLE
W3C-compliant media player

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#44]
# Summary
 product/service conforms to the W3C [Making Audio and Video Media Accessible](https://www.w3.org/WAI/media/av/) guidelines including support for closed caption and transcript files such as WebVTT, TTML, and SRT.

# Acceptance Criteria

- [ ] W3C closed caption and transcript files are implemented

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered by #386
