### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#55]
# Summary
update the footer per the figma wire frames for DC Repository.

# Acceptance Criteria

- [x] the footer is changed to look like the screenshot below (fonts, colors, spacing, etc.)
- [x] the links are linked appropriately (to url's and the phone number on the bottom left)

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

![Image](https://user-images.githubusercontent.com/39319859/200660772-fd7f642c-627d-4c62-a111-92b1544cad87.png)

# Notes
this look and feel is already implemented at https://digital.lib.utk.edu/. use that site to reference where the links should link out to.

**Comment by DiemBTran** [comment]
Linked items:

Relates to:
- EPIC: UTK Branding

**Comment by AKFosterDev** [comment]
PR ready for review [#186](https://github.com/scientist-softserv/utk-hyku/pull/186)

### QA Steps

- This footer only applies to the DC Repository theme. The trace repository will be styled later.
- QA on staging at [https://dc.utk-hyku-staging.notch8.cloud/](https://dc.utk-hyku-staging.notch8.cloud/)
-[ ] On DC Repository theme the footer should look like this: 

https://user-images.githubusercontent.com/39319859/203663657-70f3f4d5-4f49-48ea-8cfd-5a428ed68b71.mov

- All other themes should look like the defaults

**Default home**
![default home](https://user-images.githubusercontent.com/39319859/203663812-78f0e43f-aa3a-4224-8e59-61eed1f2640c.JPG)

**Cultural repository**
![cultural repository](https://user-images.githubusercontent.com/39319859/203663821-30b8efb2-2caa-4e22-904e-535c93880182.JPG)

**Institutional repository**
![institutional repository](https://user-images.githubusercontent.com/39319859/203663830-148c8398-f829-4cb2-aedb-4a537a12d38f.JPG)

**Neutral repository**
![neutral repository](https://user-images.githubusercontent.com/39319859/203663841-875e8bc0-cf03-4291-ae98-0ff55ec36beb.JPG)

**Trace repository**
![trace repository](https://user-images.githubusercontent.com/39319859/203663855-9c4f1157-bfc1-450c-9e78-55768b31be9c.JPG)

**Comment by ShanaLMoore** [comment]
## QA Results

### DC TENANT theme:

- [x] footer: 
![Image](https://user-images.githubusercontent.com/10081604/204565152-93f529ba-8db1-47e4-aa67-9b5bcff3b10f.png)

- [x] responsive: 



![Image](https://user-images.githubusercontent.com/10081604/204568949-b63ab739-c42f-4c89-b5de-7540fb5a2a9a.gif)



@AKFosterDev All of the footer links work except for Course Reserves. It links you to a [500 error page](https://dc.utk-hyku-staging.notch8.cloud/access/course-reserves/). 
I think the domain should be www.lib.utk.edu

https://www.lib.utk.edu/access/course-reserves/

### DEFAULT theme: 


![Image](https://user-images.githubusercontent.com/10081604/204566797-0936595f-d695-4af4-8565-36eaee6a6268.png)

### CULTURAL theme: 


![Image](https://user-images.githubusercontent.com/10081604/204567408-2af7a963-2831-4934-b56f-1b29e6edf828.png)

## INSTITUTIONAL theme: 


![Image](https://user-images.githubusercontent.com/10081604/204567517-836767b8-1f22-4a67-9a25-9671f9f59054.png)

### NEUTRAL theme: 


![Image](https://user-images.githubusercontent.com/10081604/204567629-17da92aa-7d2f-48ff-a888-fddd78d6676e.png)

### TRACE theme: 


![Image](https://user-images.githubusercontent.com/10081604/204567768-1d0c5e6e-0449-4432-ba30-adae792f53d8.png)

**Comment by AKFosterDev** [comment]
@ShanaLMoore The link to "Course Reserves" is broken on their live site as well. 
![Screenshot 2022-11-29 at 8 11 17 AM](https://user-images.githubusercontent.com/39319859/204582494-956c2d6d-127a-4a4b-a8e3-70f94975991c.JPG)

**Comment by ShanaLMoore** [comment]
restating this from slack to keep track of the convo in github. Could you try updating the domain of the link? 

https://www.lib.utk.edu/access/course-reserves/ leads the user to a valid page



![Image](https://user-images.githubusercontent.com/10081604/204585578-85dd3b9e-0deb-4067-8365-76654bc13dd8.png)

**Comment by AKFosterDev** [comment]
PR ready for review - https://github.com/scientist-softserv/utk-hyku/pull/236

### Summary
 Update broken footer link to course reserves

### Screenshot
![image](https://user-images.githubusercontent.com/39319859/204587942-4b6a59aa-8380-46d3-a5b4-7c547fa09ab6.png)

**Comment by kirkkwang** [comment]
Footer is looking great! All links render to the correct pages from what I can and it looks like the mock up.

**Comment by markpbaggett** [comment]
This looks good to me, but I have one quick question.  Is the footer appearing on public pages like the Work / Attachment page covered in this ticket, or will that be elsewhere?

In case I'm not clear, here is a [link and image](https://dc.utk-hyku-staging.notch8.cloud/concern/images/5b979c8c-d574-42fb-852b-2ae0ebc58ac3?locale=en) describing what I mean:



![Image](https://user-images.githubusercontent.com/2692416/205695842-7f65073f-9ca0-4648-9558-f1404520092e.png)

**Comment by AKFosterDev** [comment]
Hi @markpbaggett.

Thank you for mentioning this. The custom footer will be added to these pages as they are being worked on for the custom theming. This PR is specific to the look and behavior of the custom footer partial.

**Comment by markpbaggett** [comment]
@AKFosterDev awesome. Looks great.  😎
