### ISSUE TITLE
[5]navigation bar

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#65]
# Summary
update the navigation bar per the figma wire frames (applies to both tenants). note that the nav bar displays beneath the hero image on the home page.

# Acceptance Criteria

- [ ] the navigation bar is changed to look like the screenshot below (fonts, colors, spacing, etc.)
- [ ] the links are linked appropriately (to url's)

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

![Image](https://user-images.githubusercontent.com/29311858/202289563-ca494e1e-856c-428c-beee-b30a8feb24a1.png)

**Comment by AKFosterDev** [comment]
PR ready for review https://github.com/scientist-softserv/utk-hyku/pull/122

## Screenshots
The number of collections and works have been hard coded for these screenshots to show the functionality. Commit reverts this back to being dynamically populated.

### XL Screen
![xl 1900px](https://user-images.githubusercontent.com/39319859/200443715-9ab8626b-fadb-40b3-8bb5-8cba5d0f22c4.JPG)

### LG Screen
![lg 1200px](https://user-images.githubusercontent.com/39319859/200443755-6618403f-da53-4e91-a26a-1a5a882a0fff.JPG)

### MD Screen
![md 991px](https://user-images.githubusercontent.com/39319859/200443785-f472464d-f4ab-40a8-81ae-910b399efbcc.JPG)

### SM Screen
![sm 603px](https://user-images.githubusercontent.com/39319859/200443816-47564ca9-a95f-48ca-982d-fe0a528fffd6.JPG)

### Dropdown w/hover
![dropdown w hover](https://user-images.githubusercontent.com/39319859/200443851-fc5aae48-0ef3-44e6-9516-03dc2f4d6d8d.JPG)

**Comment by ShanaLMoore** [comment]
disregard the above comment. It may not be related. I was testing this on the qa tenant instead of the dc tenant. 

This passes QA! 🎉 



![Image](https://user-images.githubusercontent.com/10081604/201386927-4b85768d-5ee1-4d1c-aefb-f417a8ccecd8.png)


clicking Search: 




![Image](https://user-images.githubusercontent.com/10081604/201390296-977949ea-5351-4fb2-8615-d7bcabb5599d.png)

**Comment by markpbaggett** [comment]
Looks good to me.  :shipit:
