### ISSUE TITLE
Export for preservation

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#75]
# Summary
For preservation, if the fileset has a property with pcdmuse: preservation or original, it is preservation across everything

# Acceptance Criteria

- [ ] Export for preservation is implemented

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
related to #18
