### ISSUE TITLE
Viewer (or manifest) can follow order of documents

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#77]
# Summary
Each fileset should have 0-1 iana:next and 0-1 iana:prev properties that point to either the next or previous fileset in the sequence. It also has a pcdm:memberOf property that points at the book. The book should have a pcdm:hasMember property that points at each page fileset and one iana:first and one iana:last properties that point to the first and last page of the work.

# Acceptance Criteria

- [ ] Viewer (or manifest) can follow order of documents

# Screenshots or Video

# Testing Instructions

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered by #358
