### ISSUE TITLE
Added Ability to Customize the look and feel of individual collections

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#8]
# Summary

This proposal covers custom work to enhance theming at the collection level. Estimated cost range will be dependent on further details of the requirements beyond standard Hyku page views. It generally assumes UTK would require custom work outside Hyku’s built in offerings.

# Acceptance Criteria

# Screenshots/Videos

# Testing Instructions

# Notes

**Comment by jillpe** [comment]
no longer in scope 2023-04-19
