### ISSUE TITLE
Test: Generic Work Types

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#89]
# Summary
Over-arching Goal: Test Generic work type against UTK's requirements.

# Acceptance Criteria

- [x] No IIIF manifest should represent a generic work and thus no viewer.
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below
- [ ] Users should be able to easily download the primary filesets.
- [ ] Like other work types, image works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record in an OAI set for each corresponding collection to which the work belongs.

# Screenshots or Video
Screenshots available via [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/1_generic.html)

# Testing Instructions

# Notes
[UTK's generic works type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/1_generic.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
