### ISSUE TITLE
Test: Video Work Types

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/utk-hyku#91]
# Summary
Over-arching Goal: Test Video work type against UTK's requirements.

# Acceptance Criteria

- [ ] Video works should have caption or transcript files and may have them in multiple languages.
- [ ] Video works may have hierarchical structure described by metadata properties that should be converted into IIIF Presentation v3 structures and ranges.
- [ ] A video work may have other filesets of any mime type available to the user for download.
- [ ] Video works should be rendered to the user in a IIIF presentation viewer like IIIF React Media Player, Universal Viewer, Clover IIIF, or Mirador.
- [ ] the viewer display our different caption files and that these are stored in the corresponding IIIF manifest as an annotation with a motivation of supplementing in the annotations property in line with the IIIF presentation v3 specification and W3C Web Annotations specification.
- [ ] Item should pop out into a new window in location-based viewer
- [ ] Rights statements to be actionable and render the appropriate badge and usage information to the user in both the IIIF viewer (when metadata is on) and in our metadata display below
- [ ] Users should be able to easily download the primary filesets.
- [ ] video works should be represented by an OAI-PMH record based on its metadata application profile. The work should be a record of an OAI set for each corresponding collection to which the object belongs. 

# Screenshots or Video
Screenshots are available via the [link](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/3_video.html)

# Testing Instructions

# Notes
[UTK's video works type](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/3_video.html)

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by jillpe** [comment]
covered in #47
